/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maven_GetDataCpp */

#ifndef _Included_maven_GetDataCpp
#define _Included_maven_GetDataCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     maven_GetDataCpp
 * Method:    fun
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_maven_GetDataCpp_fun
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
