/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_JavaClass */

#ifndef _Included_test_JavaClass
#define _Included_test_JavaClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JavaClass
 * Method:    fun
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_JavaClass_fun
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
